package(
    default_visibility = ["//visibility:public"],
)

filegroup(
    name = "atmega16m1",
    srcs = [
        "atmega16m1.ld",
    ],
)

filegroup(
    name = "atmega328p",
    srcs = [
        "atmega328p.ld",
    ],
)
